import { Fragment } from "react";
import React, { useState, useEffect } from "react";
import { Layout } from "antd";
import Head from "next/head";
import SiderLayout from "./SiderLayout";
import HeaderLayout from "./HeaderLayout";
import { Content, Footer } from "antd/lib/layout/layout";
import { Grid } from "antd";
import Sider from "antd/lib/layout/Sider";
import {
  DashboardOutlined,
  SettingOutlined,
  LikeOutlined,
  AppstoreOutlined,
  FileOutlined,
  FormOutlined,
} from "@ant-design/icons";

function getItem(label, key, icon, children, type) {
  return {
    key,
    icon,
    children,
    label,
    type,
  };
}

function AdminLayout(props) {
  const [collapsed, setCollapsed] = useState(false);
  const [title, setTitle] = useState("");
  const { useBreakpoint } = Grid;
  const { md } = useBreakpoint();
  useEffect(() => {
    if (md) setCollapsed(false);
    else setCollapsed(true);
  }, [md]);

  const items = [
    getItem(
      "DashBoard",
      "/admin/dashboard",
      <DashboardOutlined className="sidebar-icon" />
    ),
    // getItem("Activity", "sub1", <SettingOutlined />, [
    //   getItem("Submenu", "sub3", null, [
    //     getItem("Option 7", "7"),
    //     getItem("Option 8", "8"),
    //   ]),
    // ]),
    getItem(
      "Reviews",
      "/admin/review/management",
      <FormOutlined className="sidebar-icon " />
    ),
    // getItem("Team", "team", <AppstoreOutlined className="sidebar-icon" />, [
    //   getItem("Groups", "/admin/team/groups"),
    //   getItem("Members", "/admin/team/members"),
    // ]),
    getItem(
      "Team",
      "/admin/team/members",
      <AppstoreOutlined className="sidebar-icon " />
    ),
    getItem(
      "Applaud",
      "/admin/applaud",
      <LikeOutlined className="sidebar-icon " />
    ),

    getItem(
      "Settings",
      "setting",
      <SettingOutlined className="sidebar-icon " />,
      [
        // getItem("Templates", "/admin/template "),
        // getItem("Users", "/admin/user"),
        getItem("Templates", "/admin/template"),
        getItem("Profile ", "/admin/profile "),
      ]
    ),
  ];

  return (
    <Fragment>
      <Head>
        <title>Review App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <SiderLayout
          collapsed={collapsed}
          setCollapsed={setCollapsed}
          items={items}
          setTitle={setTitle}
        />
        <Layout>
          <Content className="bg-color-dashboard ">
            {/* <HeaderLayout /> */}
            <HeaderLayout title={title} />
            {props.children}
          </Content>
          <Footer className="text-center bg-color-dashboard">
            Review App ©2021 Created by Zasya Solution
          </Footer>
        </Layout>
      </Layout>
    </Fragment>
  );
}

export default AdminLayout;
