import { Fragment } from "react";
import React, { useState } from "react";
import { Layout } from "antd";
import Head from "next/head";
import SiderLayout from "./SiderLayout";
import HeaderLayout from "./HeaderLayout";

function AdminLayout(props) {
  const [collapsed, setCollapsed] = useState(false);
  return (
    <Fragment>
      <Head>
        <title>Review App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <SiderLayout collapsed={collapsed} />
        <Layout>
          <HeaderLayout setCollapsed={setCollapsed} collapsed={collapsed} />

          {props.children}
        </Layout>
      </Layout>
    </Fragment>
  );
}

export default AdminLayout;
