import { Fragment } from "react";
import React, { useState, useEffect } from "react";
import { Layout } from "antd";
import Head from "next/head";
import SiderLayout from "./SiderLayout";
import HeaderLayout from "./HeaderLayout";
import { Content, Footer } from "antd/lib/layout/layout";
import { Grid } from "antd";

function AdminLayout(props) {
  const [collapsed, setCollapsed] = useState(false);
  const { useBreakpoint } = Grid;
  const { md } = useBreakpoint();
  useEffect(() => {
    if (md) setCollapsed(false);
    else setCollapsed(true);
  }, [md]);

  return (
    <Fragment>
      <Head>
        <title>Review App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <SiderLayout collapsed={collapsed} setCollapsed={setCollapsed} />
        <Layout>
          <Content>
            <HeaderLayout />
            {props.children}
          </Content>
          <Footer className="text-center bg-gray-200">
            Review App ©2021 Created by Zasya Solution
          </Footer>
        </Layout>
      </Layout>
    </Fragment>
  );
}

export default AdminLayout;
