import { Fragment } from "react";
import MainNavigation from "./main-navigation";
import Footer from "./footer";
import Head from "next/head";

function Layout(props) {
  return (
    <Fragment>
      <Head>
        <title>Review App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainNavigation user={props.user} />
      <main>{props.children}</main>
      <Footer />
    </Fragment>
  );
}

export default Layout;
