import React, { useState } from "react";
import {
  MailOutlined,
  SettingOutlined,
  AppstoreOutlined,
  UserOutlined,
} from "@ant-design/icons";
import { Menu, Layout } from "antd";
import { useRouter } from "next/router";
import Head from "next/head";

const { Sider } = Layout;
function getItem(label, key, icon, children, type) {
  return {
    key,
    icon,
    children,
    label,
    type,
  };
}

function SiderLayout({ collapsed }) {
  const router = useRouter();

  const items = [
    getItem("DashBoard", "/admin/dashboard", <MailOutlined />),
    getItem("Activity", "sub1", <SettingOutlined />, [
      getItem("Submenu", "sub3", null, [
        getItem("Option 7", "7"),
        getItem("Option 8", "8"),
      ]),
    ]),
    getItem("Team", "team", <AppstoreOutlined />, [
      getItem("Groups", "/admin/team/groups"),
      getItem("Members", "/admin/team/members"),
    ]),
    getItem("Users", "/admin/user", <UserOutlined />),
  ];

  const onClickSideTab = (e) => {
    if (e.key.includes("/")) router.replace(e.key);
  };
  return (
    <Sider
      trigger={null}
      collapsible
      collapsed={collapsed}
      className="  bg-white"
      width={300}
    >
      <Head>
        <title>Review App</title>
        <meta name="description" content="Generated by next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex justify-center items-center bg-cyan-500 h-20">
        <p className="text-white text-xl font-serif font-bold leading-normal mt-0 mb-2">
          Review App
        </p>
      </div>
      <div className="py-4 px-6">
        <Menu
          onClick={onClickSideTab}
          mode="inline"
          defaultSelectedKeys={router?.pathname}
          className="dashboard-sider border-0 "
          items={items}
        />
      </div>
    </Sider>
  );
}

export default SiderLayout;
