import React, { useState } from "react";
import {
  MailOutlined,
  SettingOutlined,
  AppstoreOutlined,
  UserOutlined,
  FormOutlined,
} from "@ant-design/icons";
import { Menu, Layout } from "antd";
import { useRouter } from "next/router";
import Head from "next/head";

const { Sider } = Layout;
function getItem(label, key, icon, children, type) {
  return {
    key,
    icon,
    children,
    label,
    type,
  };
}

function SiderLayout({ collapsed }) {
  const router = useRouter();

  const items = [
    getItem(
      "DashBoard",
      "/admin/dashboard",
      <MailOutlined style={{ fontSize: "18px" }} />
    ),
    // getItem("Activity", "sub1", <SettingOutlined />, [
    //   getItem("Submenu", "sub3", null, [
    //     getItem("Option 7", "7"),
    //     getItem("Option 8", "8"),
    //   ]),
    // ]),
    getItem(
      "Reviews",
      "/admin/review/management",
      <FormOutlined style={{ fontSize: "18px" }} />
    ),
    getItem("Team", "team", <AppstoreOutlined style={{ fontSize: "18px" }} />, [
      getItem("Groups", "/admin/team/groups"),
      getItem("Members", "/admin/team/members"),
    ]),

    getItem(
      "Settings",
      "setting",
      <SettingOutlined style={{ fontSize: "18px" }} />,
      [
        getItem("Templates", "/admin/template"),
        getItem("Users", "/admin/user"),
        getItem("Template View", "/admin/form/formview"),
      ]
    ),
  ];

  const onClickSideTab = (e) => {
    if (e.key.includes("/")) router.replace(e.key);
  };
  return (
    <Sider
      trigger={null}
      collapsible
      collapsed={collapsed}
      className="  bg-white"
      width={250}
    >
      <Head>
        <title>Review App</title>
        <meta name="description" content="Generated by next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="h-screen fixed top-0 md:left-0  overflow-y-auto flex-row flex-nowrap overflow-hidden shadow-xl bg-white z-10 py-4 px-6 transition-all duration-300">
        <div className="flex-col items-stretch min-h-full flex-nowrap px-0 relative">
          <a className="mt-3 text-center w-full inline-block">
            <h1 className="text-gray-900 first-line: text-xl font-serif font-bold leading-normal mt-0 mb-2">
              Review App
            </h1>
          </a>

          <div className=" flex flex-col py-4 px-6">
            <hr className=" min-w-full" />
            <Menu
              onClick={onClickSideTab}
              mode="inline"
              defaultSelectedKeys={router?.pathname}
              className="dashboard-sider border-0 gap-2 text-sm font-light rounded-lg bg-gradient-to-tr from-light-blue-500 to-light-blue-700 text-white shadow-md "
              items={items}
            />
          </div>
        </div>
      </div>
    </Sider>
  );
}

export default SiderLayout;
